apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: default
spec:
  selector:
    app: reporting-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP