version: '3.8'

services:
  customer-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=customer_service
      - POSTGRES_PASSWORD=customer_service_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=customer_service
    depends_on:
      db:
        condition: service_healthy  # Change this line
    networks:
      - customer-network
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=customer_service
      - POSTGRES_PASSWORD=customer_service_pass
      - POSTGRES_DB=customer_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - customer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customer_service -d customer_service"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s  # Add this line

networks:
  customer-network:
    driver: bridge

volumes:
  postgres_data: