apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reporting-virtualservice
  namespace: default
spec:
  hosts:
  - "reporting.example.com" 
  gateways:
  - crm-gateway
  http:
  - match:
    - uri:
        prefix: /api/reports  
    route:
    - destination:
        host: reporting-service
        port:
          number: 3000
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 2s