version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: sales
      DB_USER: sales_user
      DB_PASSWORD: sales_pass
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sales
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: sales_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: