apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  
  features:
    - name: pubsub.enabled
      enabled: true
    - name: statestore.enabled
      enabled: true

  metric:
    enabled: true

  secrets:
    scopes:
      - storeName: "statestore"
        defaultAccess: "allow"
      - storeName: "pubsub"
        defaultAccess: "allow"