apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: default
spec:
  selector:
    app: sales-service
  ports:
  - protocol: http  
    port: 80
    targetPort: 80
  type: ClusterIP